In [1]:
import numpy as np

def find_rank(matrix):
  """Finds the rank of a matrix.

  Args:
    matrix: A NumPy array representing the matrix.

  Returns:
    The rank of the matrix.
  """

  return np.linalg.matrix_rank(matrix)

# Example usage:

matrix = np.array([[1, 2, 3], [2, 4, 7], [2, 4, 5]])

rank = find_rank(matrix)
print(matrix)
print("Rank of the above matrix:", rank)

[[1 2 3]
 [2 4 7]
 [2 4 5]]
Rank of the above matrix: 2
